name: Build and Push Docker Images

on:
  # AJOUT : Déclencheur pour un lancement manuel
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Which image to build? (select "all" to build everything)'
        required: true
        type: choice
        default: 'all' # Option par défaut
        options:
          - all
          # PHP - FPM
          - 'rem42/php-camalo:8.3-fpm-alpine-latest'
          - 'rem42/php-camalo:8.4-fpm-alpine-latest'
          - 'rem42/php-camalo:8.5-fpm-alpine-latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Optionnel : empêche l'annulation des autres jobs si un job de la matrice échoue.
      matrix:
        dockerfile:
          # PHP - FPM
          - { path: './php-camalo/8.3.fpm-alpine.Dockerfile', tag: 'rem42/php-camalo:8.3-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php-camalo/8.4.fpm-alpine.Dockerfile', tag: 'rem42/php-camalo:8.4-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }
          - { path: './php-camalo/8.5.fpm-alpine.Dockerfile', tag: 'rem42/php-camalo:8.5-fpm-alpine-latest', platforms: 'linux/amd64,linux/arm64' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # AJOUT : La condition est maintenant ici
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && (
            github.event.inputs.image_tag == 'all' ||
            github.event.inputs.image_tag == matrix.dockerfile.tag
          ))
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        # AJOUT : La condition est également ici
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && (
            github.event.inputs.image_tag == 'all' ||
            github.event.inputs.image_tag == matrix.dockerfile.tag
          ))
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile.path }}
          push: true
          tags: ${{ matrix.dockerfile.tag }}
          platforms: ${{ matrix.dockerfile.platforms }}
